-- 03_stations.sql  (YOUR TURN)
-- Goal: one row per station: station_id, station_name, lat, lng, total_starts.
-- Used for the Tableau map and later for the GIS (neighborhood) join.
--
-- Hints:
--   * A station's name can change over time, so the same ID may appear with
--     two names. Pick the most common one:
--       APPROX_TOP_COUNT(start_station_name, 1)[OFFSET(0)].value
--   * Coordinates jitter slightly per ride; AVG(start_lat), AVG(start_lng) is fine.
--   * GROUP BY start_station_id.
--
-- Check your work: station_id should be unique. Verify with
--   SELECT station_id, COUNT(*) FROM ... GROUP BY 1 HAVING COUNT(*) > 1
-- (should return no rows).
